# Setup
title: Home
email: sandro.rabitti@gmail.com
description: Questo è il sito di Polaris
#url: https://getpoole.com
url:
paginate: 1
baseurl: ""
permalink: pretty
markdown: kramdown
highlighter: rouge

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Sandro Rabitti
  email: sandro.rabitti@gmail.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: About
    url: /about

  - title: Attrezzatura
    url: /pagine/attrezzatura

  - title: Vecchie_barche
    url: /pagine/vecchie_barche

  - title: Blog
    url: /archive

  - title: Crociere/Log
    url: /pagine/crociere_log

  - title: Foto/video
    url: /pagine/foto_video

  - title: Meteo
    url: /pagine/meteo



theme: jekyll-theme-cayman
